# Generated by Django 5.0.6 on 2024-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_recovery_token_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('ENTERTAINMENT', 'entertainment'), ('TECHNOLOGY', 'technology'), ('SPORTS', 'sports'), ('FOOD', 'food'), ('TOURISM', 'tourism'), ('CULTURE', 'culture'), ('ART', 'art'), ('POLITICS', 'politics'), ('SCIENCE', 'science'), ('FASHION', 'fashion'), ('CURIOSITIES', 'curiosities'), ('RANDOM', 'random')], default='random', max_length=255),
        ),
        migrations.AddField(
            model_name='poll',
            name='code',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='tags',
            field=models.CharField(blank=True, help_text='Coloque as telas separadas por #', max_length=255),
        ),
        migrations.DeleteModel(
            name='RecoveryToken',
        ),
    ]
