from rest_framework_simplejwt.views import TokenObtainPairView
from app.serializers.customTokenObtainPairSerializer import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer